apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  namespace: openfaas-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - image: mongo
          name: mongodb
          ports:
            - containerPort: 27017
          resources: {}
          # lifecycle:
          #   postStart:
          #     exec:
          # command: ['/bin/sh']
          # args:
          #   [
          #     '-c',
          #     'mongo -u admin -p password --authenticationDatabase admin test',
          #   ]
          # command:
          # - /bin/bash
          # - -c
          # mv is not needed for later versions e.g. 3.4.19 and 4.1.7
          # - mongo -u admin -p password --authenticationDatabase admin test
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password2
            # - name: MONGODB_USERNAME
            #   value: admin
            # - name: MONGODB_PASSWORD
            #   value: password
            # - name: MONGODB_DATABASE
            #   value: ebliq
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      restartPolicy: Always
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata
status: {}
