apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata
  namespace: openfaas-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  namespace: openfaas-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/mongo_data'
