apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: openfaas-db
spec:
  type: NodePort
  ports:
    - name: 'db-port'
      port: 27017
      targetPort: 27017
      nodePort: 31705
  selector:
    io.kompose.service: mongodb
status:
  loadBalancer: {}
