apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: openfaas-db
spec:
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
  selector:
    io.kompose.service: mongodb
status:
  loadBalancer: {}
