apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: openfaas-db
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
  - name: db-port
    nodePort: 31704
    port: 5432
    protocol: TCP
  selector:
    app: postgres
